#!/usr/bin/env bash
# Check if an argument is provided
	if [ $1 -eq 0 ]; then
	    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
        exit 1
    fi
#ping the adress IP
    ping -c 5 "$1"
